config/routes.rb
Myapp::Application.routes.draw do
  get '/' => 'home#index', as: :home
  get '/userhome' => 'home#user_home'
  get '/contact' => 'users#contact'
  get '/about' => 'users#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'alternate_layout'
	def index
		
	end
	def user_home
		
	end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
	layout 'application'
	def contact
		
	end
	def about
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_urgent_message.html.erb
<%= message[:title] %>
<br>
<%= message[:text] %>
<br>
<%= message[:ending]%>

app/views/home/index.html.erb
<h1>Index</h1>

<%= render 'urgent_message', message: {title:'This is my partial', text:'LALALALALALALALALA', ending:'Using partials are fun :)'} %>

app/views/home/user_home.html.erb
<h1>User Home</h1>

app/views/layouts/alternate_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav>
		<ul>
			<li>
				<%= link_to('Home',home_path)%>
			</li>
			<li>
				<%= link_to('UserHome',userhome_path) %>
			</li>
			<li>
				<%= link_to('About',about_path) %>
			</li>
			<li>
				<%= link_to('Contact',contact_path) %>
			</li>
		</ul>
	</nav>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		This is my header
	</header>
	<nav>
		<li>
			<%= link_to('Home',home_path) %>
		</li>
	</nav>

<%= yield %>
	<footer>
		This is my footer
	</footer>
</body>
</html>

app/views/users/about.html.erb
<h1>About</h1>

app/views/users/contact.html.erb
<h1>Contact</h1>